namespace Storix.Application.DTO.Products
{
    /// <summary>
    /// Data Transfer Object for Top Products display
    /// </summary>
    public class TopProductDto
    {
        /// <summary>
        /// Unique identifier for the product
        /// </summary>
        public int ProductId { get; set; }

        /// <summary>
        /// Product ranking position (1-5)
        /// </summary>
        public int Rank { get; set; }

        /// <summary>
        /// Name of the product
        /// </summary>
        public string ProductName { get; set; }

        /// <summary>
        /// SKU of the product
        /// </summary>
        public string SKU { get; set; }

        /// <summary>
        /// Total revenue generated by the product
        /// </summary>
        public decimal TotalRevenue { get; set; }

        /// <summary>
        /// Number of units sold
        /// </summary>
        public int UnitsSold { get; set; }

        public TopProductDto()
        {

        }

        /// <summary>
        /// Data Transfer Object for Top Products display
        /// </summary>
        public TopProductDto( int productId,
            int rank,
            string productName,
            string sku,
            decimal totalRevenue,
            int unitsSold )
        {
            ProductId = productId;
            Rank = rank;
            ProductName = productName;
            SKU = sku;
            TotalRevenue = totalRevenue;
            UnitsSold = unitsSold;
        }
    }
}
